# Generated by Django 2.2.5 on 2019-11-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usstocklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market',
            field=models.CharField(max_length=10, verbose_name='市場'),
        ),
        migrations.CreateModel(
            name='Usstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5, verbose_name='ティッカー')),
                ('stockname', models.CharField(max_length=255, verbose_name='銘柄名')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usstocklist.Market', verbose_name='市場')),
            ],
        ),
    ]
