# Generated by Django 2.2.5 on 2019-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usstocklist', '0002_auto_20191124_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='usstock',
            name='ticker',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ティッカー'),
        ),
    ]
